"""removed field unique

Revision ID: 19e779257907
Revises: 9c6f13b05ae9
Create Date: 2024-09-17 15:05:59.636441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e779257907'
down_revision: Union[str, None] = '9c6f13b05ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permission_url_path', table_name='permission')
    op.create_index(op.f('ix_permission_url_path'), 'permission', ['url_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_url_path'), table_name='permission')
    op.create_index('ix_permission_url_path', 'permission', ['url_path'], unique=1)
    # ### end Alembic commands ###
