"""update models permission

Revision ID: 76da6f352648
Revises: ef71e2a42333
Create Date: 2024-09-17 14:29:34.009172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76da6f352648'
down_revision: Union[str, None] = 'ef71e2a42333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('uid', sa.String(), nullable=False))
    op.create_index(op.f('ix_permission_uid'), 'permission', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_uid'), table_name='permission')
    op.drop_column('permission', 'uid')
    # ### end Alembic commands ###
