"""add fields in permission model

Revision ID: 9c6f13b05ae9
Revises: 76da6f352648
Create Date: 2024-09-17 14:41:37.059144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6f13b05ae9'
down_revision: Union[str, None] = '76da6f352648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('method', sa.String(), nullable=True))
    op.add_column('permission', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'name')
    op.drop_column('permission', 'method')
    # ### end Alembic commands ###
