"""add model permission

Revision ID: ef71e2a42333
Revises: 
Create Date: 2024-09-14 11:04:34.640793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef71e2a42333'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permission_url_path', table_name='permission')
    op.create_index(op.f('ix_permission_url_path'), 'permission', ['url_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_url_path'), table_name='permission')
    op.create_index('ix_permission_url_path', 'permission', ['url_path'], unique=False)
    # ### end Alembic commands ###
